Allow to start/stop the docker service within the dropdown menu
gpouilloux/gnome-shell-extension-docker pull request #17
Opened 2017-08-26 02:43 UTC by faidoc

![image](https://user-images.githubusercontent.com/331390/29738002-5383771a-89de-11e7-9cf2-c481e92dd82c.png)
![image](https://user-images.githubusercontent.com/331390/29738006-64ba87a8-89de-11e7-8a93-240093a9dbcd.png)

2018-04-14 22:28 UTC, hoshsadiq commented
@faidoc Any updates on this? These options would be pretty cool to have

2018-05-24 09:11 UTC, mduft commented
I tried this in the gnome-shell 3.28.2-1 on fedora 28. Works like a charm. I will keep using this version as I love the functionality to open a terminal :) Thanks. Hopefully accepted upstream soon!

2019-04-19 21:40 UTC, gpouilloux requested changes
It requires additional effort to make it work

2019-04-19 21:42 UTC, hoshsadiq commented on src/dockerMenuItem.js
> +            cmd += this.defaultTerminal + ' -- docker exec -it ' + this.containerName + ' /bin/bash';
Also bash isn't always installed on a container.

2019-05-07 19:35 UTC, rderooy commented on src/dockerMenuItem.js
> +            cmd += this.defaultTerminal + ' -- docker exec -it ' + this.containerName + ' /bin/bash';
By default /bin/sh should be used, which should be a symlink to the actual shell. In most cases, it will just point to /bin/bash.

2020-05-09 16:54 UTC, gpouilloux commented
Open terminal feature will be supersedes by this pull request (See https://github.com/gpouilloux/gnome-shell-extension-docker/pull/48)

There are still the good idea of being able to start/stop docker daemon that should be cherry-picked though

2020-05-28 19:47 UTC, gpouilloux commented
Declined in favor of #53

2020-05-28 19:47 UTC, closed without merging